### ISSUE TITLE
ss-watchdog这个怎么用？

### ISSUE THREAD

**Issue by piscesmk2013** [houzi-/tomato-shadowsocks#10]
脚本6.0，用的方案4，最后提示ss-watchdog失败，虽然好像没啥影响，不过问问这个文件是干嘛的啊？

**Comment by jefferycn** [comment]
我也遇到一样的问题, 把 /opt/bin/ss-watchdog 重新从 git 上复制一份就好了. 但是, 我用方案4还遇到很多其他问题,总跑不起来. 比如:

```
 You want to close the proxy?(y/N)
y
  Turn off...              done. 
 Flushing rules... Bad argument `WANPREROUTING'
Try `iptables -h' or 'iptables --help' for more information.
             done. 
```

**Comment by houzi-** [comment]
这个是执行规则的脚本，如果执行不了，规则也就加载不上去！

**Comment by houzi-** [comment]
由于开发DD-WRT的shadowsocks所以精力有限，这个6.0版本测试不充分就推送上去了！如果需要远程协助的请联系我的邮箱，这样解决问题总比说来的更直接高效！
