### ISSUE TITLE
最新版确实安装不上 tomato mips

### ISSUE THREAD

**Issue by guixiaomin** [houzi-/tomato-shadowsocks#11]
我研究了一个通宵。。。。确实。。。。。。。。。安装不上。伤心。。。。。我很想用。。能抽点时间检查下脚本吗？

**Comment by guixiaomin** [comment]
对了。tomato版本是136。。。。。

**Comment by jefferycn** [comment]
我都弄了2天了, 之前用很老的版本用得好好的..我就不该想试试 pcap_dnsproxy
我是128版本, 480MHz cpu, 16MB flash, 8Mb jffs
建议能否出一个精简版本,能直接在jffs上安装 pcap_dnsproxy. 比如resolveip,diff这些库就不要安装了..

**Comment by houzi-** [comment]
@guixiaomin 提问题的时候麻烦带上路由器的型号和架构！

**Comment by houzi-** [comment]
@jefferycn现在路由器都是普遍的都是16M以上的闪存了！还带USB！我弄个精简版本支持的意义不大！精简很简单就是把set_up的检验功能砍了！就可以随便安装一个或者多个方案的ipk

**Comment by houzi-** [comment]
实在抱歉了，害这位同学搞了一个通宵(⊙_◎)，由于开发DD-WRT的shadowsocks所以精力有限，这个6.0版本测试不充分就推送上去了！如果需要远程协助的请联系我的邮箱，这样解决问题总比说来的更直接高效！

**Comment by jefferycn** [comment]
嗯，所以我在自己砍。我昨天接了个usb，安装过程各种死机…只有用jffs更稳定。
谢谢，之后有问题我再这里跟帖请求帮助！
你的脚本给了很大的帮助😄

Sent from my phone.

On Fri, May 20, 2016 at 6:57 PM -0700, "hackshell" notifications@github.com wrote:

@jefferycn现在路由器都是普遍的都是16M以上的闪存了！还带USB！我弄个精简版本支持的意义不大！精简很简单就是把set_up的检验功能砍了！就可以随便安装一个或者多个方案的ipk

**Comment by houzi-** [comment]
@jefferycn USB是不会造成死机的吧

**Comment by guixiaomin** [comment]
hg320烽火 硬件能力超级小 16兆 唉 mips方案 可怜啊 jffs 才9m多 唉 装不上 昨晚老被ipk下载坑 删除jffs木用 必须要重新格式化 才能安装

**Comment by guixiaomin** [comment]
我今晚usb试试

**Comment by RockZhou8** [comment]
同要求出精简版！
我是N16，ROM是32的，但刷的是20多MB的tomato之后，JFFS只有11MB多，5.08版本开始就会在安装过程中自动生成entware的backup文件，导致塞满了jffs空间而最终安装失败。

**Comment by houzi-** [comment]
如果有USB的尽量用USB挂载U DISK来配置！

**Comment by guixiaomin** [comment]
@houzi- 搜噶。。。。。看来我们的10M 小jffs不行。。。可我U盘 读写速度超级快。舍不得啊。o(︶︿︶)o 唉
