### ISSUE TITLE
选的program_2 安装和配置都成功也重启了路由器 但是路由器下的设备并不能翻墙

### ISSUE THREAD

**Issue by flzyup** [houzi-/tomato-shadowsocks#12]
RT，选的：ss-redir+chnroutes+chinadns+pdnsd
端口列表：
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:9091            0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:5353            0.0.0.0:\*               LISTEN
tcp        0      0 192.168.100.1:139       0.0.0.0:\*               LISTEN
tcp        0      0 192.168.1.3:8080        0.0.0.0:\*               LISTEN
tcp        0      0 192.168.100.1:80        0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:53              0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:1080            0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:51515           0.0.0.0:\*               LISTEN
tcp        0      0 192.168.100.1:445       0.0.0.0:\*               LISTEN
tcp        0      0 127.0.0.1:1054          0.0.0.0:\*               LISTEN
tcp        0      0 :::5353                 :::\*                    LISTEN
tcp        0      0 :::53                   :::\*                    LISTEN
tcp        0      0 :::22                   :::\*                    LISTEN
tcp        0      0 :::23                   :::\*                    LISTEN
tcp        0      0 :::51515                :::\*                    LISTEN
进程列表：
949 root      1032 S    eapd
  951 root      1508 S    nas
 1014 root      1516 S    telnetd -p 23
 1032 root      1056 S    dropbear -p 22 -a
 1035 root      1032 S    eapd
 1041 root      1508 S    nas
 1078 nobody    1600 S    dnsmasq -c 1500 --log-async
 1081 root         0 SW   [kjournald]
 1088 root      1540 S    crond -l 9
 1092 root      1056 S    rstats
 1095 root      1064 S    cstats
 1100 root         0 SW   [flush-8:0]
 1129 root      3504 S    cron
 1133 root      1948 S    ss-redir -c /opt/etc/shadowsocks.json
 1146 root       352 S    chinadns -p 5353 -c /opt/etc/chnroute.txt -s 180.168.255.118,116.228.111.18,127.0.0.1:1054
 1164 nobody   30320 S    pdnsd -c /opt/etc/pdnsd.conf -p /opt/var/run/pdnsd.pid
 1184 root      186m S    Pcap_DNSProxy --config-file /opt/etc/pcap-dnsproxy
 1315 root      1528 S    udhcpc -i vlan2 -b -s dhcpc-event -H unknown -O 33 -O 121 -O 249 -m -p /var/run/udhcpc-wan.pid
 2244 root      1120 S    dropbear -p 22 -a
 2245 root      1540 S    -sh
 2854 root      2352 S    nmbd -D
 2855 root      2304 S    nmbd -D
 2961 root      2812 S    httpd
 2964 root      3064 S N  smbd -D
 3005 root     16996 S    /usr/bin/transmission-daemon -g /opt/btconfig/.settings
 3006 root     16996 S    /usr/bin/transmission-daemon -g /opt/btconfig/.settings
 3007 root     16996 S    /usr/bin/transmission-daemon -g /opt/btconfig/.settings
 3008 root     16996 S    /usr/bin/transmission-daemon -g /opt/btconfig/.settings
 3046 root     16996 S    /usr/bin/transmission-daemon -g /opt/btconfig/.settings
 3857 root      1520 S    /bin/sh -c /usr/sbin/watchdog
 3858 root      1520 S    /bin/sh -c /usr/sbin/watchdog alive
 3859 root      1520 S    {watchdog} /bin/sh /usr/sbin/watchdog
 3860 root      1516 S    {watchdog} /bin/sh /usr/sbin/watchdog alive
 3871 root      1520 R    ps
 3872 root      1516 S    {watchdog} /bin/sh /usr/sbin/watchdog alive
 3874 root      1512 R    echo google.com,microsoft.com
 3875 root      1516 S    sed s/,/ /
 3876 root      1520 R    {watchdog} /bin/sh /usr/sbin/watchdog

似乎都起来了，有什么需要修改的吗？要用-g使用global 路由器下的设备才能被正确路由？

**Comment by houzi-** [comment]
麻烦报一下路由器的型号和架构！
-g是全局模式(⊙o⊙)哦！
由于开发DD-WRT的shadowsocks所以精力有限，这个6.0版本测试不充分就推送上去了！如果需要远程协助的请联系我的邮箱，这样解决问题总比说来的更直接高效！

**Comment by flzyup** [comment]
Name    TomatoUSB
Model   Asus RT-N18U
Chipset ARMv7 Processor rev 0 (v7l)
CPU Freq    800 MHz (single-core)
Flash Size  128MB

Processor   : ARMv7 Processor rev 0 (v7l)
processor   : 0
BogoMIPS    : 1599.07

Features    : swp half thumb fastmult edsp
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x3
CPU part    : 0xc09
CPU revision    : 0

Hardware    : Northstar Prototype
Revision    : 0000
Serial      : 0000000000000000
路由器信息如上

**Comment by guixiaomin** [comment]
@houzi- ,因为已经有一台爱快了。不想 花费多余的钱去折腾梅林，请问烽火hg320 这种mips,16M闪存的机器。jffs勉强能安装进去吗？

**Comment by guixiaomin** [comment]
@houzi- 版本还是暂时用5?
