### ISSUE TITLE
6.1版本起不对mipsel进行更新

### ISSUE THREAD

**Issue by houzi-** [houzi-/tomato-shadowsocks#14]
https://github.com/houzi-/tomato-shadowsocks/commit/aa6b26b970b25912418833ebe3d59e7d69d10356

**Comment by houzi-** [comment]
相关的配套IPK也不再进行更新！

**Comment by guixiaomin** [comment]
@houzi- 那6.1还有效不？之后的版本没了是吧？

**Comment by houzi-** [comment]
有效！

**Comment by RockZhou8** [comment]
实测我的N16装不上6.1 mipsel，还是
-sh shadowosocks not found

**Comment by houzi-** [comment]
@RockZhou8 重新下载！

**Comment by RockZhou8** [comment]
@houzi- wow,好速度！试试去

**Comment by RockZhou8** [comment]
找了个U盘，开装了，刚重启了路由器 为了消bug

**Comment by houzi-** [comment]
@RockZhou8 如果有问题重新开个issues来讨论！

**Comment by houzi-** [comment]
@guixiaomin @RockZhou8 重新更新修复mips的部分BUG
