### ISSUE TITLE
6.2-stable mipsel ss-redir failed.

### ISSUE THREAD

**Issue by RockZhou8** [houzi-/tomato-shadowsocks#16]
Your Choice:
3
 Set programs_3...
 INFO:  Configuring dnsmasq_custom...
sed: /mnt/sda1/shadowsocks/dnsmasq.d/accelerated-domains.china.conf: No such file or directory
 Updating chnroutes...              done.
.
Done.
 Starting ss-redir...              failed.
 Starting chinadns...              done.
 Starting dnscrypt-proxy...              done.
 Starting cron...              done.
 Loading ipset module...              done.
/mnt/sda1/shadowsocks/shadowsocks: line 1433: /opt/etc/init.d/S99ss-rules: Permission denied
 Loading iptables rules...              done.
 INFO:  Configuring ntp server...
 INFO:  Configuring turn startup items and guard the capital...
Commit... done.
 Starting dnscrypt-proxy...              already running.
 You want to backup entware?(y/N)
n
 PASS.
 Set successfully, please reboot the router.
 Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/tomato-shadowsocks/issues.

**Comment by RockZhou8** [comment]
手动shadowsocks -S

Done.
 Starting ss-redir...              failed.
 Starting chinadns...              already running.
 Starting dnscrypt-proxy...              done.
 Starting cron...              already running.

**Comment by houzi-** [comment]
单独只执行看看错误

```
ss-redir -c /opt/etc/shadowsocks.json -v
```

**Comment by houzi-** [comment]
实在无法部署成功，联系我的邮箱，我远程看看什么问题！

**Comment by ghost** [comment]
我的R6300v2 部署后也是ss-redir failed.

root@unknown:/tmp/home/root# shadowsocks  -S
.....
Done.
 Starting ss-redir...              failed.
 Starting chinadns...              already running.
 Starting dnscrypt-proxy...              done.
 Starting cron...              already running.

**Comment by houzi-** [comment]
单独执行这个

```
ss-redir -c /opt/etc/shadowsocks.json -v
```

然后截取错误的信息给我！

**Comment by houzi-** [comment]
必须使用shadowsocks-libev提供中提供的最新的ss-rules和ss-watchdog

**Comment by ghost** [comment]
单独执行这个

ss-redir -c /opt/etc/shadowsocks.json -v
然后截取错误的信息给我！
\

root@unknown:/tmp/home/root# ss-redir -c /opt/etc/shadowsocks.json -v
-sh: ss-redir: Permission denied

**Comment by ghost** [comment]
好像是权限禁止了  
楼主最新的5月22日的armv7_shadowsocks  无法执行，提示找不到文件，我用了5月18日的shadowsocks就继续下去了

**Comment by houzi-** [comment]
@wwwxxxz
@RockZhou8 
赋予可执行的权限就OK了！

**Comment by houzi-** [comment]
@wwwxxxz 请使用今天更新的armv7的脚本和shadowsocks-libev吧！
