### ISSUE TITLE
ss信息都填准确了，网络就是上不去

### ISSUE THREAD

**Issue by ghost** [houzi-/tomato-shadowsocks#19]
弄了好几天了，今天弄到半夜还在弄，选了2模式后就是百度也开不了了，好多网页也打不开 ，谷歌打不开，然后切换成全局模式也一样，但楼主这页面又能打开

**Comment by houzi-** [comment]
请提供详细信息出来，不然没办法解决问题！
列如:nslookup www.youtube.com
贴出这个信息！

**Comment by ghost** [comment]
root@unknown:/tmp/home/root# nslookup www.youtube.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.youtube.com
Address 1: 200:2:807:c62d::
Address 2: 173.194.72.100 tf-in-f100.1e100.net
Address 3: 173.194.72.102 tf-in-f102.1e100.net
Address 4: 173.194.72.113 tf-in-f113.1e100.net
Address 5: 173.194.72.138 tf-in-f138.1e100.net
Address 6: 173.194.72.101 tf-in-f101.1e100.net
Address 7: 173.194.72.139 tf-in-f139.1e100.net
root@unknown:/tmp/home/root# nslookup www.baidu.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'www.baidu.com'
root@unknown:/tmp/home/root# nslookup www.google.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.google.com
Address 1: 2404:6800:4005:802::2004 hkg12s02-in-x04.1e100.net
Address 2: 216.58.221.132 hkg07s02-in-f4.1e100.net
root@unknown:/tmp/home/root# nslookup www.youku.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'www.youku.com'
root@unknown:/tmp/home/root# nslookup www.xunlei.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'www.xunlei.com'
root@unknown:/tmp/home/root# nslookup github.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      github.com
Address 1: 192.30.252.129 github.com

亲，能告诉我该怎木操作么？

**Comment by houzi-** [comment]
知道怎么回事了？ 去/opt/bin 目录里，把ss-rules修改如下:(找到这一部分)

```
#   $IPT -I PREROUTING -p udp --dport 53 \
#       -j REDIRECT --to-ports 5353
```

**Comment by ghost** [comment]
亲，找到了，这个就如你所写的
fw_rule() {
    $IPT -N SS_SPEC_WAN_FW && \
    $IPT -A SS_SPEC_WAN_FW -p tcp \
        -j REDIRECT --to-ports $local_port 2>/dev/null || {
        loger 3 "Can't redirect, please check the iptables."
        exit 1
    }

# $IPT -I PREROUTING -p udp --dport 53 \

```
    -j REDIRECT --to-ports 5353
return $?
```

}

**Comment by ghost** [comment]
额 我不知道该怎木改。。

**Comment by houzi-** [comment]
那就等我有有时间修复吧！

wwwxxxz notifications@github.com于2016年6月1日周三 22:03写道：

> 额 我不知道该怎木改。。
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/houzi-/tomato-shadowsocks/issues/19#issuecomment-223002189,
> or mute the thread
> https://github.com/notifications/unsubscribe/AI9fG1azlcWSxdGa4Ti3uFYsW4Kbg2hNks5qHZFCgaJpZM4Iq3LP
> .
> 
> ## 

JasonLin

**Comment by houzi-** [comment]
照我截图那样子修改！
![default](https://cloud.githubusercontent.com/assets/9395995/15735088/5e4e398c-28c8-11e6-8eba-ea8b1674d1fe.PNG)

**Comment by houzi-** [comment]
https://github.com/houzi-/tomato-shadowsocks/commit/2175c9a57ae1442a78d554395df004101b362e29

**Comment by ghost** [comment]
昨天后来我也把#  给加到下一栏的前面去了，还是一样诶，huozi啥时有空能否远程一下？

**Comment by houzi-** [comment]
QQ：674949301
问题：maybe

今晚远程看一下！

2016-06-02 17:44 GMT+08:00 wwwxxxz <notifications@github.com>:
