### ISSUE TITLE
v6.2-stable EA6700安装不成功。

### ISSUE THREAD

**Issue by itachiccc** [houzi-/tomato-shadowsocks#20]
型号：EA6700
固件：AdvancedTomato 3.1-136 或者 tomato-EA6700-AT-ARM2.6-136-AIO-64K
开启了JFFS分区，所需的ipk全都放在tmp目录下了.
第一次执行报错：You do not import the entire IPK!
第二次执行报错：OPT directory does not mount.
然后。就没有然后了。

**Comment by houzi-** [comment]
This is not the script BUG!
You have to plug in accordance with the above given uploaded to the router, not the whole

**Comment by itachiccc** [comment]
没全部啊，就是你所说的那些包。一个没多一个没少。

**Comment by houzi-** [comment]
你的包上传重复将会导致**You do not import the entire IPK!**
第一次失败后要重启然后再配置！否则会出现**OPT directory does not mount**
这并不是脚本的BUG

**Comment by itachiccc** [comment]
啊。好的好的，我再试试。

**Comment by itachiccc** [comment]
= =
楼下有人，也不好意思重启路由。
估计是resolvip_0.1(not necessary)这个锅，我看你写了不是必须的，所以就没传这个包。
然而shell又写了-a -e $SCRIPT_DIR/resol*。。

**Comment by houzi-** [comment]
是的！我下个版本才会去掉！

**Comment by itachiccc** [comment]
安装完了，过程也没报错，然而还是翻不出去。
用手机客户端和PC客户端没问题，应该排除了IP或者密码输错的可能。
服务端挂在EC2上，加密方式是aes-256-cfb。。

**Comment by houzi-** [comment]
使用哪个方案？确定一下是否DNS污染

**Comment by itachiccc** [comment]
你推荐的方案3啊。
shadowsocks -S && shadowsocks -f && shadowsocks -r的时候报了个错：
/opt/bin/shadowsocks: line 1472: /opt/etc/init.d/S99ss-rules: Permission denied

**Comment by houzi-** [comment]
把ss-rules

**Comment by houzi-** [comment]
加上权限

**Comment by itachiccc** [comment]
wtf。。EA真是太恶心，boot失败就从另外一个分区重新引导了。每次都要重新 30 30 30 然后再刷一次tt。。

**Comment by houzi-** [comment]
由于你的ss-rules没有运行成功导致规则没有正确加载

**Comment by itachiccc** [comment]
加了权限不报错了。还是翻不出去。
我试试看刷回tomato吧(现在用的AdvancedTomato)

**Comment by itachiccc** [comment]
Local Server Port这个用1080？

**Comment by houzi-** [comment]
建议1080

**Comment by houzi-** [comment]
其他端口也可以

**Comment by houzi-** [comment]
直接联系我的邮箱，我远程帮你看看
