### ISSUE TITLE
6.1 - Mispel on RT-N66U (Shibby 136) 脚本运行失败

### ISSUE THREAD

**Issue by ungo918** [houzi-/tomato-shadowsocks#22]
搞了一整个晚上，不知道问题出在那里，请指点，谢谢！

Router: ASUS RT-N66U
Firmware: tomato-K26USB-1.28.RT-N5x-MIPSR2-136-AIO-64K
JFFS: Enabled

运行过程：

```
root@unknown:/tmp/home/root#` chmod +x /tmp/shadowsocks
root@unknown:/tmp/home/root# /tmp/shadowsocks -su
 INFO:  Creating in...
Connecting to pkg.entware.net (81.4.123.217:80)
-                    100% |*******************************|  1359   0:00:00 ETA
Info: Creating folders...
Info: Deploying opkg package manager...
Downloading /opt/bin/opkg... success!
Downloading /opt/etc/opkg.conf... success!
Downloading /opt/etc/profile... success!
Downloading /opt/etc/init.d/rc.func... success!
Downloading /opt/etc/init.d/rc.unslung... success!
Info: Basic packages installation...
Downloading http://pkg.entware.net/binaries/mipsel/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/entware-ng.
Installing ldconfig (1.0.13-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/ldconfig_1.0.13-3_mipselsf.ip                                                                                        k.
Installing findutils (4.6.0-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/findutils_4.6.0-1_mipselsf.ip                                                                                        k.
Installing libc (1.0.13-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libc_1.0.13-3_mipselsf.ipk.
Installing libgcc (5.3.0-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libgcc_5.3.0-3_mipselsf.ipk.
Installing libssp (5.3.0-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libssp_5.3.0-3_mipselsf.ipk.
Configuring ldconfig.
Configuring libgcc.
Configuring libc.
Configuring libssp.
Configuring findutils.

Congratulations! If there are no errors above then Entware-ng is successfully initialized.

Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues

Type 'opkg install <pkg_name>' to install necessary package.

[: /tmp/shadowsocks-libev_2.4.6-RE_mipselsf.ipk: unknown operand
 You do not import the entire IPK!

```

再次运行：

```
root@unknown:/tmp/home/root# /tmp/shadowsocks -su
 SHADOWSOCKS already installed!
 PLATFORM: PASS.
 SHADOWSOCKS: PASS.
 MOUNT: PASS.
ls: chinadns: No such file or directory
ls: Pcap_DNSProxy: No such file or directory
ls: ss-redir: No such file or directory
ls: resolvip: No such file or directory
ls: pdnsd-ctl: No such file or directory
ls: diff: No such file or directory
ls: dnscrypt-proxy: No such file or directory
ls: curl: No such file or directory
ls: crontab: No such file or directory
ls: bash: No such file or directory
 DNSMASQ: ERROR.
 ZONEINFO_ASIA: ERROR.
/tmp/shadowsocks: line 1433: diff: not found
 DEPENDENCE:
 ERROR.
 WARNING:
 Please install the following software:
shadowsocks-libev
chinadns
pdnsd
pcap-dnsproxy
resolvip
diffutils
dnscrypt-proxy
curl
crontab
dnsmasq
zoneinfo_asia
bash
```

**Comment by houzi-** [comment]
上传指定的ipk,不要全部上传！

**Comment by ungo918** [comment]
我会再试试，但我重试一过程中也不断遇到entware抽风的情况，有两个问题：
1. 如果装了一半抽风了导致运行失败，有什么办法可以重新安装吗？目前我都是整个tomato重刷一遍，非常费时麻烦
2. 我有个pptp vpn，但设了vpn client以后，看似状态也是连接了，但实际连网还在墙内 

感谢！

**Comment by houzi-** [comment]
如果安装失败不用重新刷写，只要把脚本安装的所在分区删除即可！

**Comment by ungo918** [comment]
谢谢你的提示，但我把jffs底下的/jffs底下都删了，还是有一样的错误，请问还有那些目录要删吗？
另外，抽风的问题我想用PPTP VPN Client来解决，配好了以后看起来是连上了，但是试了下google都还是连不上，请问是我少配了什么吗？

新手问题比较多，请多包涵，但也非常感谢你的帮忙！

On Jul 02, 2016, at 08:37 PM, hackshell notifications@github.com wrote:

如果安装失败不用重新刷写，只要把脚本安装的所在分区删除即可！

**Comment by ungo918** [comment]
你好，

抱歉再次打扰你，我想问一下以下错误信息是否说明我的JFFS空间不够？
但奇怪的是我的朋友也是用RT-N66U，但他可以成功跑完…

谢谢帮忙！

> root@unknown:/tmp/home/root# chmod +x /tmp/shadowsocks
> root@unknown:/tmp/home/root# /tmp/shadowsocks -su
> INFO: Creating in...
> Connecting to pkg.entware.net (81.4.123.217:80)
> - 100% |*******************************| 1359 0:00:00 ETA
>   Info: Creating folders...
>   Info: Deploying opkg package manager...
>   Downloading /opt/bin/opkg... success!
>   Downloading /opt/etc/opkg.conf... success!
>   Downloading /opt/etc/profile... success!
>   Downloading /opt/etc/init.d/rc.func... success!
>   Downloading /opt/etc/init.d/rc.unslung... success!
>   Info: Basic packages installation...
>   Downloading http://pkg.entware.net/binaries/mipsel/Packages.gz.
>   Updated list of available packages in /opt/var/opkg-lists/entware-ng.
>   Installing ldconfig (1.0.13-3) to root...
>   Downloading http://pkg.entware.net/binaries/mipsel/ldconfig_1.0.13-3_mipselsf.ip k.
>   Installing findutils (4.6.0-1) to root...
>   Downloading http://pkg.entware.net/binaries/mipsel/findutils_4.6.0-1_mipselsf.ip k.
>   Installing libc (1.0.13-3) to root...
>   Downloading http://pkg.entware.net/binaries/mipsel/libc_1.0.13-3_mipselsf.ipk.
>   Installing libgcc (5.3.0-3) to root...
>   Downloading http://pkg.entware.net/binaries/mipsel/libgcc_5.3.0-3_mipselsf.ipk.
>   Installing libssp (5.3.0-3) to root...
>   Downloading http://pkg.entware.net/binaries/mipsel/libssp_5.3.0-3_mipselsf.ipk.
>   Configuring ldconfig.
>   Configuring libgcc.
>   Configuring libc.
>   Configuring libssp.
>   Configuring findutils.
> 
> Congratulations! If there are no errors above then Entware-ng is successfully in itialized.
> 
> Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues
> 
> Type 'opkg install <pkg_name>' to install necessary package.
> 
> Installing chinadns (1.3.2) to root...
> Installing pdnsd (1.2.9-e02a81d9e63927e93dc49d218535c880623bcd77) to root...
> Installing libpthread (1.0.13-3) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/libpthread_1.0.13-3_mipselsf. ipk.
> Installing pcap_dnsproxy (0.4.5.6-1) to root...
> Installing libsodium (1.0.10-1) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/libsodium_1.0.10-1_mipselsf.i pk.
> Installing libpcap (1.7.4-1) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/libpcap_1.7.4-1_mipselsf.ipk.
> Installing libstdcpp (5.3.0-3) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/libstdcpp_5.3.0-3_mipselsf.ip k.
> Installing resolvip (0.1) to root...
> Unknown package 'shadowsocks'.
> Installing shadowsocks-libev (2.4.6-RE) to root...
> Installing diffutils (3.3-3-DEV) to root...
> Installing dnscrypt-proxy (1.6.1-DEV) to root...
> Installing curl (7.47.2-DEV) to root...
> Installing dnsmasq (2.7.5) to root...
> Installing cron (4.1-2) to root...
> Installing zoneinfo-asia (2016b-1) to root...
> Installing bash (4.3.42-1a) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/bash_4.3.42-1a_mipselsf.ipk.
> Installing libncurses (6.0-1) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/libncurses_6.0-1_mipselsf.ipk .
> Installing terminfo (6.0-1) to root...
> Downloading http://pkg.entware.net/binaries/mipsel/terminfo_6.0-1_mipselsf.ipk.
> Configuring terminfo.
> Configuring shadowsocks-libev.
> Configuring libpthread.
> Configuring diffutils.
> Configuring libsodium.
> Configuring libpcap.
> Configuring libstdcpp.
> Configuring pcap_dnsproxy.
> Configuring libncurses.
> Configuring bash.
> Configuring cron.
> Configuring dnscrypt-proxy.
> Configuring zoneinfo-asia.
> Configuring dnsmasq.
> Configuring pdnsd.
> Configuring chinadns.
> Configuring curl.
> Configuring resolvip.
> Collected errors:
> - opkg_install_cmd: Cannot install package shadowsocks.
>   SHADOWSOCKS script installed successfully!
>   cp: write error: No space left on device
>   PLATFORM: PASS.
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   /tmp/shadowsocks: line 1433: can't create /opt/etc/init.d/auto.run: No space lef t on device
>   chmod: /opt/etc/init.d/auto.run: No such file or directory
>   ln: /opt/bin/auto.run: No space left on device
>   SHADOWSOCKS: PASS.
>   MOUNT: PASS.
>   DNSMASQ: PASS.
>   ZONEINFO_ASIA: PASS.
>   DEPENDENCE: PASS.
>   ============================================
>   Please input your shadowsocks account information:
>   (Your Server IP):
>   (Your Server Port):
>   (Your Local Port):
>   (Your Password):
>   (Your Encryption Method):aes-256-cfb
>   ============================================
>   Please confirm your shadowsocks information:
>   Your Server IP: 
>   Your Server Port: 
>   Your Server Port: 
>   Your Password: 
>   Your Encryption Method: aes-256-cfb
>   ============================================
>   /tmp/shadowsocks: line 1433: can't create /opt/var/log/resolvip_tmp.txt: No spac e left on device
>   cat: can't open '/opt/var/log/resolvip_tmp.txt': No such file or directory
>   [: 202: unknown operand
>   /tmp/shadowsocks: line 1433: can't create /opt/var/log/resolvip.txt: No space le ft on device
>   sed: /opt/var/log/resolvip.txt: No such file or directory
>   WARNING: Can not write the configuration information, please re-enter your:
>   shadowsocks set_up

On Jul 02, 2016, at 08:37 PM, hackshell notifications@github.com wrote:

如果安装失败不用重新刷写，只要把脚本安装的所在分区删除即可！

**Comment by ungo918** [comment]
我试着插USB，但按照教程的方式格式化为ext3/4后，挂载不上router...，插回windows / mac都无法格式化，真是每条路都被断呀...

请救救我，谢谢

**Comment by houzi-** [comment]
email联系我吧！
