### ISSUE TITLE
6.2-stable 成功部署后无法运行

### ISSUE THREAD

**Issue by EasyingFreeman** [houzi-/tomato-shadowsocks#23]
Xiaomi R1D 研究了一天，因为只有16M的Flash，所以不能挂载JFFS分区，只能使用内置的硬盘，PREFIX=/tmp/mnt/sda4，-su之后一切正常，使用了模式3，重启后我重新挂载了sda4，然后-S时出现

`sed: /opt/etc/shadowsocks.json: No such file or directory
mount: mounting /opt/sbin/dnsmasq on /usr/sbin/dnsmasq failed: No such file or directory
/tmp/mnt/sda4/data/shadowsocks/shadowsocks/shadowsocks: line 1472: /opt/etc/init.d/S22shadowsocks: not found
/tmp/mnt/sda4/data/shadowsocks/shadowsocks/shadowsocks: line 1472: /opt/etc/init.d/S26pdnsd: not found
/tmp/mnt/sda4/data/shadowsocks/shadowsocks/shadowsocks: line 1472: /opt/etc/init.d/S24chinadns: not found
/tmp/mnt/sda4/data/shadowsocks/shadowsocks/shadowsocks: line 1472: /opt/etc/init.d/S00timezone: not found
/tmp/mnt/sda4/data/shadowsocks/shadowsocks/shadowsocks: line 1472: /opt/etc/init.d/S10cron: not found
`

在sda4下明明有这些文件，而且权限全是7777，但还是一直提示找不到，然后就一直卡在最后一步了

**Comment by houzi-** [comment]
没有挂载到/opt目录，没必要手动挂载或者使用其他挂载脚本挂载！因为shadowsocks脚本都会自动挂载的
