### ISSUE TITLE
please add failover for multi-SS-server on Tomato!

### ISSUE THREAD

**Issue by 88922493** [houzi-/tomato-shadowsocks#25]
Hi,
   more and more SS-server failed after I add them. Can you add a new function to switch to another SS-server after one by one once the main one is dead.

thanks

**Comment by houzi-** [comment]
Have ss-server switching function, see the script help

**Comment by 88922493** [comment]
```
 is it automatic ?  I mean script will detect the way to inside web and outside web (google or youtobe) to see if it's normal, then make a decision. if the current SS-server is not working, it should switch to next predefined SS-server (more than 2 predefined SS-servers).
 Someone has done it for OpenWrt, but I don't know there is a same version for your script or not. if not, please add it for mipsel shibby. 
 please confirm again.
```

**Comment by houzi-** [comment]
This is not automatic, it does not intend to add.If you want this feature! So you only have to add one

**Comment by 88922493** [comment]
oh, I am not good at code. later, if you have some free time, please consider my suggestion, for you just less than five mins.  refer to attachment.
[Openwrt_Shadowsocks_AutoSwitch-master.zip](https://github.com/houzi-/tomato-shadowsocks/files/460747/Openwrt_Shadowsocks_AutoSwitch-master.zip)

**Comment by houzi-** [comment]
I see it
