### ISSUE TITLE
脚本会导致旧版本advancedtomato设备列表显示不全，导致最新版设备列表不显示

### ISSUE THREAD

**Issue by ilasx** [houzi-/tomato-shadowsocks#26]
脚本会导致旧版本advancedtomato固件的设备列表显示不全，导致最新版固件设备列表不显示。报错

> 
Connection lost!
Attempting to reconnect...

> ERROR - 504
The Graphical user interface was unable to communicate with the router!
These issues usually occur when a file is missing, web handler is busy or the connection to router is unavailable.

Refreshing browser window might help.
这里有图片
[https://bitbucket.org/AndreDVJ/advancedtomato-arm/commits/beef649b3b829bbcac373052909a0bdbf47e1c1d](url)

**Comment by flzyup** [comment]
我刷了AdvTomato也是 是因为脚本导致的？

**Comment by ilasx** [comment]
无意间找到原因了，外挂的dnsmasq和内置有冲突，改用自带就好了

**Comment by houzi-** [comment]
@ilasx 
请使用该项目:
https://github.com/koolshare/ttsoft
部署教程:
http://koolshare.cn/thread-101344-1-1.html
