### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by joopdo** [houzi-/tomato-shadowsocks#27]
On Netgear w7000 I had to do a number of things to get this to work.

! your script -su function can remove /jffs/opt (in a number of locations). Please ask user to confirm instead, as some of us run opkg/entware and more critical dependencies here! 

(in random order)

1. /opt/etc/init.d/S99ss-rules does not exist. (doing manually now)
2. Give ota (auth) manually to /opt/etc/shadowsocks.json
3. seems like chinadns init.d name is changed from 24 to 56
4. pdnsd is deprecated, needs alternative.
5. -su deps check pcap_dnsproxy when installed still fails due to different foldername
6. rename crontab to cron (i presume it's the same)
7. needed bash as well (add as requirement)
8. dependency zoneinfo_asia  is zoneinfo-asia 
9. missing dep' opkg install libstdcpp (for pcap_dnsproxy)
10 installed dnsmasq-full

Maybe unrelated but not all ipk's are in my machine's repo. I had to swithc opkg to http://pkg.entware.net/binaries/armv7/Packages.html

**Comment by houzi-** [comment]
Please use this project, this project is no longer maintained
https://github.com/koolshare/ttsoft
