### ISSUE TITLE
Pcap_DNSProxy and dnscrypt-proxy have moved to sbin

### ISSUE THREAD

**Issue by j796160836** [houzi-/tomato-shadowsocks#29]
Hi, I used your script are so nice, but meet some problem during the install.

I found these two package will fail when checking dependency script
- Pcap_DNSProxy
- dnscrypt-proxy

Please update the auto-configure script when you have free time.
I'm looking forward to your new scripts, thanks.

**Comment by houzi-** [comment]
Please use this project, this project is no longer maintained
https://github.com/koolshare/ttsoft
