### ISSUE TITLE
entware installer 脚本地址该更新了~~

### ISSUE THREAD

**Issue by xsharp** [houzi-/tomato-shadowsocks#4]
@see https://github.com/Entware-ng/Entware-ng/wiki/Install-on-the-TomatoUSB

**Comment by houzi-** [comment]
目前我没没有测试自己编译的ipk是否能够无错误地安装与entware-ng兼容，或者请你测试一下，如果成功发个PR给我，这样搞比较保险一点！

**Comment by houzi-** [comment]
@xsharp 
https://github.com/houzi-/tomato-shadowsocks/blob/master/mipsel/shadowsocks#L77
