### ISSUE TITLE
我之前是4.9.4，现在重新装v5.0-2有如下提示（已erase jffs)

### ISSUE THREAD

**Issue by RockZhou8** [houzi-/tomato-shadowsocks#5]
5.0-2是
mipsel_shadowsocks.zip
package是V5.0-miselsf(entware-ng

>  /tmp/shadowsocks set_up
>  INFO:  Creating in...
> wget: bad address 'pkg.entware.net'
> /tmp/shadowsocks: line 1713: opkg: not found
>  SHADOWSOCKS script installed successfully!
>  PLATFORM: PASS.
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> /tmp/shadowsocks: line 1713: can't create /opt/etc/init.d/auto.run: nonexistent                                                                                                                                                              directory
> chmod: /opt/etc/init.d/auto.run: No such file or directory
> ln: /opt/bin: File exists
>  SHADOWSOCKS: PASS.
>  MOUNT: PASS.
> /tmp/shadowsocks: cd: line 1713: can't cd to /opt/bin
> ls: chinadns: No such file or directory
> ls: Pcap_DNSProxy: No such file or directory
> ls: ss-redir: No such file or directory
> ls: resolvip: No such file or directory
> ls: pdnsd-ctl: No such file or directory
> ls: diff: No such file or directory
> ls: dnscrypt-proxy: No such file or directory
> ls: curl: No such file or directory
>  DNSMASQ:
>  ERROR.
>  WARNING:
>  Please install the following software:
> dnsmasq-full

**Comment by houzi-** [comment]
entware-ng没有安装完整

**Comment by houzi-** [comment]
建议你wget一下该源地址时候畅通

**Comment by houzi-** [comment]
5.0-2版本替换了自带的dnsmasq！

**Comment by RockZhou8** [comment]
重新set_up了，终于可以了，entware总抽风
