### ISSUE TITLE
dnsmasq 安装包有问题 启动脚本不存在。另外运行过程中好像不能正常启动安装的dnsmasq

### ISSUE THREAD

**Issue by ilasx** [houzi-/tomato-shadowsocks#6]

**Comment by houzi-** [comment]
因为已经安装并挂载替换自带的dnsmasq，请看/usr/sbin/dnsmasq的修改日期就知道！如果有问题请截取dnsmasq的log来看看！我这里mipsel和arm都能完整的解析和一些重要的功能都正常！

**Comment by houzi-** [comment]
想重新启动dnsmasq 就直接输入 `service dnsmasq restart`,还有你使用的是哪个方案？如果是方案一，可能是kernel的原因，因为我编译的时候没打kernel patch

**Comment by ilasx** [comment]
好吧，我就是用的方案一。

**Comment by ilasx** [comment]
你脚本里还有残留的 /opt/etc启动。。。

**Comment by ilasx** [comment]
另外提一下，你的entware安装地址不定时抽风，估计被墙了

**Comment by houzi-** [comment]
是不是方案一无法导入IP的ipset ？你可以输入`ipset -L`截取信息上来！
还有你的路由器是什么平台的？

**Comment by houzi-** [comment]
关于entware-ng这个并不是我维护的，这个如果线路抽风或者被墙的话建议挂载VPN进行配置！
其实这个问题也是老问题了，原本我想弄个绿色安装解压包，但由于entware-ng那里面的动态库文件不不断更新的，所以没办法搞！

**Comment by ilasx** [comment]
你是那个博主还是另外一个维护的？我昨天传了个cfe给你们。。不知道坑了你们没有。我现在的情况很复杂，用了你脚本大部分网站已经上不去了

**Comment by ilasx** [comment]
root@unknown:/tmp/home/root# ipset -L
Name: ss_spec_lan_ac
Type: hash:net
Revision: 0
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 8500
References: 0
Members:

Name: gfw_black_list
Type: hash:ip
Revision: 0
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 9816
References: 2
Members:
203.208.39.199
64.233.189.113
203.208.39.192
203.208.43.70
192.30.252.91
203.208.43.103
203.208.39.239
192.30.252.87
64.233.187.239
52.0.212.134
74.125.23.138
203.208.43.104
173.194.72.139
173.194.72.101
74.125.23.136
74.125.23.91
203.208.43.98
216.58.221.110
203.208.43.64
216.58.221.99
203.208.39.193
173.194.134.52
74.125.204.138
74.125.23.101
216.58.197.97
74.125.23.100
74.125.204.100
64.233.187.138
203.208.39.248
173.194.72.102
74.125.23.93
203.208.43.72
203.208.43.71
203.208.39.247
173.194.72.100
74.125.204.113
74.125.204.102
203.208.43.97
203.208.39.255
203.208.39.196
203.208.43.73
74.125.203.113
203.208.43.67
192.30.252.127
203.208.43.68
103.245.222.133
203.208.43.66
74.125.23.102
203.208.43.65
64.233.187.102
203.208.43.99
74.125.203.101
203.208.39.197
74.125.203.132
64.233.189.100
52.6.126.106
203.208.43.100
173.194.72.138
203.208.43.110
64.233.189.101
74.125.203.102
64.233.189.188
74.125.204.101
203.208.43.78
216.58.197.100
64.233.187.139
74.125.23.113
54.85.147.14
64.233.189.138
203.208.43.96
203.208.39.206
64.233.189.114
203.208.39.200
203.208.43.105
216.58.197.108
64.233.187.113
203.208.39.198
54.231.114.19
203.208.39.194
74.125.203.100
173.194.72.113
203.208.39.201
173.194.72.95
64.233.189.102
64.233.189.192
203.208.43.101
74.125.203.138
74.125.23.190
173.194.72.239
203.208.43.102
203.208.43.69
54.231.9.17
192.30.252.126
192.30.252.128
74.125.23.139
203.208.39.195
64.233.187.100
74.125.204.139
192.30.252.129
74.125.203.139
64.233.189.139
216.58.221.237
64.233.187.101
root@unknown:/tmp/home/root#

**Comment by houzi-** [comment]
你不是使用方案一的吗？这个不是方案的哦！昨天他向你要XIAOMI R1D的CFE可以用啊，木有问题，可以直接双清！

**Comment by ilasx** [comment]
这是方案一的，现在不清楚什么情况，我先换你们最新的脚本试试看。我的固件是自己编译的最新advancedtomato.应该没有多大影响

**Comment by houzi-** [comment]
这不是方案一的rules

**Comment by houzi-** [comment]
怎么会有ss_spec_lan_ac

**Comment by houzi-** [comment]
下面这个确实是gfw_black_list，并且能正确导入IP到集合里

**Comment by ilasx** [comment]
不知道，什么情况，反正我现在大部分网页进不去。个别进上。。好坑

**Comment by houzi-** [comment]
这个情况我先标记为BUG，有时间再进行测试一下，不知道其他方案有没有问题，如果其他方案没问题的话，先用其他方案的代替一下！
感谢你的反馈！good luck ψ(｀∇´)ψ

**Comment by ilasx** [comment]
好吧，实在不行我就换回老版本用着。。

**Comment by ungo918** [comment]
我也是预到entware抽风的情况，有两个问题：
1. 如果装了一半抽风了导致运行失败，有什么办法可以重新安装吗？目前我都是整个tomato重刷一遍，非常费时麻烦
2. 我有个pptp vpn，但设了vpn client以后，看似状态也是连接了，但实际连网还在墙内 

感谢！
