### ISSUE TITLE
升级5.0-8又碰到了问题，已erase jffs多次了

### ISSUE THREAD

**Issue by RockZhou8** [houzi-/tomato-shadowsocks#8]
1.第一次我把V5.0-mipselsf(entware-ng)下面不管static还是dymatic里的，都塞到了/tmp下，然后set_up之后就一直提示失败失败失败
2.然后erase jffs重来，把

> Download:shadowsocks-libev_2.4.5-1、chinadns_1.3.2、pdnsd_1.2.9a、pcap-dnsproxy0.4.5.3-1、resolvip_0.1、diffutils3.3-3 dnscrypt-proxy_1.6.1-1 curl_7.47.2-DEV(mipsel) dnsmasq-2.75 cron_4.1-2 zoneinfo-asia_2016b-1upload to the router /tmp directory

提到这么11个ipk放到/tmp下，结果告诉我
Unknown package 'shadowsocks'.
Installing shadowsocks-libev (2.4.5-1) to root...
Ignored shadowsocks-libev md5sum mismatch.
Ignored shadowsocks-libev sha256sum mismatch.

Collected errors:
- opkg_install_cmd: Cannot install package shadowsocks.
  SHADOWSOCKS script installed successfully!
  cp: write error: No space left on device
  PLATFORM: PASS.
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: No space left on device
  chmod: /opt/etc/init.d/auto.run: No such file or directory
  ln: /opt/bin/auto.run: No space left on device

我看到jffs shadowsocks下有个不小的backup 文件，似乎把我的jffs空间都给吃光了。。。
JFFS 使用率 11.17 MB / 11.38 MB (98%)

另外问下shadowsocks-libev_2.4.5-RE_mipselsf.ipk  是什么，我放过这个文件进去安装也是失败了

**Comment by RockZhou8** [comment]
删了jffs opt-backup 下的文件，jffs剩余80%空间了，我继续shadowsocks set_up，这下终于成功了

**Comment by houzi-** [comment]
@RockZhou8 **shadowsocks-libev_2.4.5-RE_mipselsf.ipk**这个是全静态编译的，opt-backup下的是entware-ng源的备份文件，是用来恢复entware-ng使用的！
