### ISSUE TITLE
每一次的升级，都像是一场赌博，而我从来没有赢过（升6.0失败，诡异）

### ISSUE THREAD

**Issue by RockZhou8** [houzi-/tomato-shadowsocks#9]
像往常一样 erase jffs,然后下载6.0的mipsel_shadowsocks，和packages里的那些个老面孔
复制到/tmp
给权限
然后随手敲入shadowsocks set_up，哦不是，这次命令是 shadowsocks -su
然后不得了的事情发生了，居然提示我
-sh: shadowsocks: not found
于是ls 一下，明明就看到shadowsocks安静的躺在列表里，winscp也能看到属性、权限0755，预览等等，一切都很正常的样子！但就是运行不了！
于是再重启 再复制再权限再安装，对不起，还是
-sh: shadowsocks: not found
于是erase jffs再重启 再复制再权限再安装，对不起，还是
-sh: shadowsocks: not found
...........
`/tmp$ chmod +x /tmp/shadowsocks`
`/tmp$ shadowsocks`
`-sh: shadowsocks: not found`
每一次的升级，都像是一场赌博，而我从来没有赢过

**Comment by houzi-** [comment]
由于在开发DD-WRT的shadowsocks,所以这个版本没有作过多的测试！知道什么问题，马上修改重新上传

**Comment by houzi-** [comment]
还有！shadowsocks-libev要2.4.6,不能使用2.4.5！

**Comment by RockZhou8** [comment]
用的就是 shadowsocks-libev_2.4.6-RE_mipselsf.ipk，每个文件都对着你的guide 一一核对了的。。。
但是很诡异的是提示shadowsocks 没找到，但是明明设置权限都能成功，没找到是个什么鬼。。。
我试试用老版本的装吧

**Comment by houzi-** [comment]
我待会上传6.0的修正版本！稍等一下

**Comment by houzi-** [comment]
已经上传了！重新尝试一下吧！还有**ss-watchdog**这个安装完第一部分还没有写入账号的时候去/opt/bin目录找到这个文件修改一下
https://github.com/houzi-/tomato-shadowsocks/commit/7f05b653aef17f20a1430bf97a2e3da2ef0e7fb0

**Comment by RockZhou8** [comment]
shadowsocks -su命令貌似不行？我重新用set_up命令安装了，
但是又被entware源坑了：
`Connecting to pkg.entware.net (81.4.123.217:80)`
`wget: error getting response`
`shadowsocks: line 2038: opkg: not found`

再次运行shadowsocks set_up提示我
`SHADOWSOCKS already installed!`
`PLATFORM: PASS.`
`shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: nonexistent directory`
`shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: nonexistent directory`
`shadowsocks: line 2038: can't create /opt/etc/init.d/auto.run: nonexistent directory`

有什么不用erase jffs就能干净重装的办法吗？每次erase+重启都得好长时间

**Comment by houzi-** [comment]
下载最新版本的，使用**-su**的

**Comment by houzi-** [comment]
其实你没必要erase,直接**rm -rf /jffs/***就可以了

**Comment by RockZhou8** [comment]
我现在就是6.0的shadowsocks，时间是2016年5月18日22点08分的

 shadowsocks -su
 # -------------------------------------------------------------------
 # Copyright (C) 2016 Jason Lin wojiaolinmu008@gmail.com
 # Last edited: 2016.4.15
 # Version: V5.0-8 (MIPS version)

**Comment by houzi-** [comment]
是可以使用-su参数的

**Comment by RockZhou8** [comment]
shadowsocks -su
 # -------------------------------------------------------------------
 # Copyright (C) 2016 Jason Lin wojiaolinmu008@gmail.com
 # Last edited: 2016.4.15
 # Version: V5.0-8 (MIPS version)
 # Explain: This script can be used only for shibby Tomato MIPS firmware.
 # Thanks: [@aa65535 @wojiaolinmu008 @tomato_shibby @asus_merlin @bwq518]
 # Description: This is a science on ShadowSocks Internet automatic
 # configuration script in Tomato under.
 # This is free software, licensed under the GNU General Public License v3.
 # See /LICENSE for more information.
 # -------------------------------------------------------------------
 =====================================================================
 WIKI:
   [set_up] Set ShadowSocks and ChinaDNS
   [run] Running ShadowSocks and ChinaDNS
   [ipset] Loading module and ipset rule
   [rules] Application Firewall Policy
   [global] Global Proxy
   [flush] Clear firewall policy
   [update] Update chnroutes Routing Host
   [update_gfwlist] Update GFWLIST domain
   [check] Guardian ss-redir
   [check_rules] Guardian iptables rules
   [ss_switch] Account switching
   [mult_switch] Multiple_switching
   [lan_ignore] LAN access control
   [off_on] Turn off switch
   [update_scr] Update script
   [rebuild_scr] Rebuild script
   [mail] Send shadowsocks running information
   [help] Script help

**Comment by houzi-** [comment]
你这个确定是6.0版本的吗？

**Comment by houzi-** [comment]
![h n ycjxcrq5 wq 59wlhy](https://cloud.githubusercontent.com/assets/9395995/15363851/ca030d60-1d4c-11e6-8c41-f9e4181d0e02.png)

**Comment by RockZhou8** [comment]
咦，我勒个去，哪儿搞错了么我。。。sorry ，我再试一下

**Comment by houzi-** [comment]
如果第一次没有成功安装**entware-ng**没有成功，建议直接重启一下路由器再来一遍！

**Comment by houzi-** [comment]
还有记得使用我先前说的命令清空/jffs分区一下！

**Comment by RockZhou8** [comment]
换6.0的命令安装是可以了，但最终我只有 11.38 MB大小的JFFS最终还是因为空间不足安装失败了，这个issue先close吧，谢谢houzi大大

**Comment by houzi-** [comment]
backup entawre这个看自己需要选择！

**Comment by RockZhou8** [comment]
我还没有到backup entware的时候 jffs已经满了。。。
今晚又尝试了多次。。。

我不想用方案4的话可以不装pcap_dnsproxy吗？这个有2.32MB之巨。。。

**Comment by houzi-** [comment]
如果没有USB那就只能你自己修改脚本来不安装pcap了

**Comment by RockZhou8** [comment]
是把这里的“pcap星号”删掉吗？
`cd $SCRIPT_DIR && opkg install --force-checksum china* pdnsd* pcap* reso* shadow* diff* dnscr* cur* dnsma* cron* zone* bash`   ·

**Comment by houzi-** [comment]
set_up里关于pcap的都删除掉

**Comment by RockZhou8** [comment]
我把6.0 set_up里的删掉，但是后面DEPENDENCE出ERROR了，缺少pcap。。。
于是现在回退5.08了，把set_up里entware backup删掉了，可以用了，目前 JFFS 使用率 10.05 MB / 11.38 MB (88%)

**Comment by houzi-** [comment]
直接加我QQ，我来远程协助你！安装个TV
674949301
问题:maybe

On Sat, May 21, 2016, 15:40 Rock Zhou <notifications@github.com> wrote:

> 我把6.0 set_up里的删掉，但是后面DEPENDENCE出ERROR了，缺少pcap。。。
> 于是现在回退5.08了，把set_up里entware backup删掉了，可以用了，目前 JFFS 使用率 10.05 MB / 11.38 MB
> (88%)
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/houzi-/tomato-shadowsocks/issues/9#issuecomment-220764167>
>
-- 

JasonLin

**Comment by houzi-** [comment]
邮箱联系我远程协助吧！
